### ISSUE TITLE
WordPress database error: [Illegal mix of collations (utf8mb3_general_ci,IMPLICIT) and (utf8mb4_unicode_520_ci,COERCIBLE) for operation

### ISSUE THREAD

**Issue by oldrup** [pojome/activity-log#203]
Thank you so much for a very fine plugin ❤

In my initial tests with WordPress 6.5 beta, and PHP 8.3, I encountered the following error, when uploading a file with an absolutely insane filename: `Øresund 🏊‍♀️ + Lillebælt er #farvand 🌊 i åh så herlige Danmark! ❤ – Photo by Benjamin Blättler on Unsplash.jpg`

![image](https://github.com/pojome/activity-log/assets/17141205/d467adab-2b21-46f8-a6d3-8ac382420a73)

WP_DEBUG enabled.

It's not a huge issue, as the file gets uploaded just fine. The action is also logged in the activity log:

![image](https://github.com/pojome/activity-log/assets/17141205/8da72ac6-5631-4b56-a759-8b8c7ac678ea)

I believe this issue was present in WP 6.4 as well; I just didn't get to mention it, as it doesn't affect the upload, really.

Database info from Site Health:
![image](https://github.com/pojome/activity-log/assets/17141205/dba45e7b-d17a-4fd2-987c-7db82082c7ea)

Is that anything you can reproduce?

**Comment by arielk** [comment]
HI @oldrup,

The issue may be due to a database encoding problem that affects special characters. Here’s a quick workaround you can try:

1. Deactivate and delete the Activity Log plugin.
2. Reinstall and activate the plugin.
3. Try uploading the file again.

**Note**: Deleting the plugin will erase your log history, so please export it first if you have important data.

We apologize for this workaround, as it seems to be a unique case, and we’re not yet sure how to solve it. Let us know if this helps!
